inherit_gem:
  rubocop-discourse: stree-compat.yml

# Still work to do in ensuring we don't link old files
Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/NoResetColumnInformationInMigrations:
  Enabled: true
